### ISSUE TITLE
Light code review

### ISSUE THREAD

**Issue by grewscant** [ganm0r/learn-mern#2]
Please take this review very lightly 😄

Keeping in mind that this is your first proper tryout and no-one's expecting the first go to be perfect, I won't be picking everything, but I'll make sure to highlight critical issues (if any), just so that you can get an idea.

I was badly discouraged after my first proper code review, hence this is not an exhaustive review. I'll leave out a few issues, just so that it's not too strong.

Will add comments here asynchronously.

**Comment by ganm0r** [comment]
> just so that it's not too strong.

I can take it. If it's bad, it's bad. I will only learn & it will actually stick with me. Any and every comment is appreciated, thanks a lot! :rocket:

**Comment by grewscant** [comment]
I think you used these to achieve custom behaviour. But these APIs are [unstable](https://caniuse.com/?search=%3A%3A-webkit-scrollbar). So, I'm sure you already know this (you mentioned using Chrome in your status), but it will only work on Chrome. So keep usage low.

https://github.com/ganm0r/prechess/blob/main/frontend/src/pages/Home.jsx#L27-L39

**Comment by grewscant** [comment]
[Here](https://github.com/ganm0r/prechess/blob/main/frontend/src/components/GameCard.jsx#L84-86), your date is being calculated on during the component-render, which for other computed values can be expensive. Move this to a constant instead.

```js
const dateFromGameUpdatedAt = new Date(game.updatedAt).toLocaleString("en-US", {
    dateStyle: "long",
})
```

then use that constant there.

**Comment by grewscant** [comment]
You don't need state here, you can populate the modal directly from `game`

https://github.com/ganm0r/prechess/blob/5b40cee0493e1d479e30076865f22c6c3f87e4a7/frontend/src/components/GameCard.jsx#L47

**Comment by ganm0r** [comment]
> I think you used these to achieve custom behaviour. But these APIs are [unstable](https://caniuse.com/?search=%3A%3A-webkit-scrollbar). So, I'm sure you already know this (you mentioned using Chrome in your status), but it will only work on Chrome. So keep usage low.
> 
> https://github.com/ganm0r/prechess/blob/main/frontend/src/pages/Home.jsx#L27-L39

Yes, tried styling scrollbar for both webkit and moz. But couldn't figure out the latter other than altering colour. And I mentioned Chrome as Chrome and Firefox align images differently. If the image is aligned perfectly in Chrome, in Firefox it is overflowing into the Masthead :cry:

**Comment by ganm0r** [comment]
I have made the other two changes. I had declared that state when initially testing the modal with dummy data and forgot to refactor. Thanks so much! :sparkling_heart:
